version: '3'
services:
  db:
    image: mysql:8.0.16
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
      --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: 'adsmanager'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'changeme'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080